export const FETCH_USER = {
    BEGIN  : 'FETCH_USER.BEGIN',
    FAILURE: 'FETCH_USER.FAILURE',
    SUCCESS: 'FETCH_USER.SUCCESS'
}

export const SUBMIT_SURVEY = {
    BEGIN  : 'SUBMIT_SURVEY.BEGIN',
    FAILURE: 'SUBMIT_SURVEY.FAILURE',
    SUCCESS: 'SUBMIT_SURVEY.SUCCESS'
}

export const FETCH_SURVEYS = {
    BEGIN  : 'FETCH_SURVEYS.BEGIN',
    FAILURE: 'FETCH_SURVEYS.FAILURE',
    SUCCESS: 'FETCH_SURVEYS.SUCCESS'
}
